In [6]:
# display top 5 rows in the dataframe
# import 
import pandas as pd
# see all columns in the .head() dataframe 
# i want to see all columns in the .head() how do i do that?
pd.set_option('display.max_columns', None)
df = pd.read_parquet("EURUSD_M1_v4.parquet")
df.head()

,time,ATR_14,dist_to_vwap_norm,EMA_10_slope_norm,dist_to_EMA_10_norm,EMA_20_slope_norm,dist_to_EMA_20_norm,EMA_50_slope_norm,dist_to_EMA_50_norm,EMA_100_slope_norm,dist_to_EMA_100_norm,EMA_200_slope_norm,dist_to_EMA_200_norm,RSI_7,RSI_14,RSI_21,stoch_7_cycle_phase,stoch_14_cycle_phase,stoch_21_cycle_phase,BB_width,BB_squeeze_rank,dist_to_bb_upper_norm,dist_to_bb_lower_norm,dist_to_sma10,asset_id,body_size,total_range,body_ratio,top_wick_ratio,bottom_wick_ratio,relative_size,candle_direction,minute_sin,minute_cos,week_min_sin,week_min_cos,day_sin,day_cos,M2_Body_Ratio,M2_Top_Wick_Ratio,M2_Bottom_Wick_Ratio,M2_Relative_Size,M3_Body_Ratio,M3_Top_Wick_Ratio,M3_Bottom_Wick_Ratio,M3_Relative_Size,M5_Body_Ratio,M5_Top_Wick_Ratio,M5_Bottom_Wick_Ratio,M5_Relative_Size,M10_Body_Ratio,M10_Top_Wick_Ratio,M10_Bottom_Wick_Ratio,M10_Relative_Size,M15_Body_Ratio,M15_Top_Wick_Ratio,M15_Bottom_Wick_Ratio,M15_Relative_Size,EMA_15_slope_norm,dist_to_EMA_15_norm,RSI_15_proxy,M15_energy_ratio,EMA_30_slope_norm,dist_to_EMA_30_norm,RSI_30_proxy,M30_energy_ratio,H1_Volatility_Rank,H1_Body_Avg,H1_Efficiency_Ratio,H1_Trend_Direction,H1_Range_Cleanliness,H1_Gap_to_VWAP,M1_Velocity_vs_M5,M1_Velocity_vs_M15,M1_Volatility_Acceleration,M1_Spread_Tax_Ratio,RSI_M1_vs_M5_delta,RSI_M1_vs_M15_delta,Slope_M1_vs_M5_delta,Slope_M1_vs_M15_delta,Vol_M1_vs_M15_ratio,Vol_M1_vs_M30_ratio,Accel_M2_to_M5,Accel_M5_to_M15,Accel_M15_to_M60,Squeeze_Flow_M1_to_M10,Squeeze_Flow_M10_to_M30,Squeeze_Flow_M30_to_M200,body_ratio_lag_1,wick_low_lag_1,wick_high_lag_1,size_atr_lag_1,body_ratio_lag_2,wick_low_lag_2,wick_high_lag_2,size_atr_lag_2,body_ratio_lag_3,wick_low_lag_3,wick_high_lag_3,size_atr_lag_3,body_ratio_lag_4,wick_low_lag_4,wick_high_lag_4,size_atr_lag_4,body_ratio_lag_5,wick_low_lag_5,wick_high_lag_5,size_atr_lag_5,body_ratio_lag_6,wick_low_lag_6,wick_high_lag_6,size_atr_lag_6,body_ratio_lag_7,wick_low_lag_7,wick_high_lag_7,size_atr_lag_7,body_ratio_lag_8,wick_low_lag_8,wick_high_lag_8,size_atr_lag_8,body_ratio_lag_9,wick_low_lag_9,wick_high_lag_9,size_atr_lag_9,body_ratio_lag_10,wick_low_lag_10,wick_high_lag_10,size_atr_lag_10,pullback_intensity,wick_pressure_ratio,momentum_cleanliness,dist_to_ph1_micro_horizontal,ph1_micro_horizontal_age,ph1_micro_horizontal_power,dist_to_pl1_micro_horizontal,pl1_micro_horizontal_age,pl1_micro_horizontal_power,dist_to_ph2_micro_horizontal,ph2_micro_horizontal_age,ph2_micro_horizontal_power,dist_to_pl2_micro_horizontal,pl2_micro_horizontal_age,pl2_micro_horizontal_power,dist_to_ph3_micro_horizontal,ph3_micro_horizontal_age,ph3_micro_horizontal_power,dist_to_pl3_micro_horizontal,pl3_micro_horizontal_age,pl3_micro_horizontal_power,ph1_structural_horizontal_power,pl1_structural_horizontal_power,dist_to_ph1_structural_horizontal,dist_to_pl1_structural_horizontal,ph1_structural_horizontal_age,pl1_structural_horizontal_age,ph2_structural_horizontal_power,pl2_structural_horizontal_power,dist_to_ph2_structural_horizontal,dist_to_pl2_structural_horizontal,ph2_structural_horizontal_age,pl2_structural_horizontal_age,ph3_structural_horizontal_power,pl3_structural_horizontal_power,dist_to_ph3_structural_horizontal,dist_to_pl3_structural_horizontal,ph3_structural_horizontal_age,pl3_structural_horizontal_age,dist_to_00_pips,dist_to_50_pips,ph1_struct_touch_count,pl1_struct_touch_count,ph2_struct_touch_count,pl2_struct_touch_count,ph3_struct_touch_count,pl3_struct_touch_count,dist_to_ph1_micro_trendline,trendline_ph1_slope_micro,slope_ph1_velocity_micro,dist_to_ph2_micro_trendline,dist_to_ph3_micro_trendline,ph1_micro_trendline_age,ph1_micro_trendline_power,ph2_micro_trendline_age,ph2_micro_trendline_power,ph3_micro_trendline_age,ph3_micro_trendline_power,trendline_ph1_micro_r2,trendline_ph2_micro_r2,trendline_ph3_micro_r2,dist_to_ph1_structural_trendline,dist_to_ph2_structural_trendline,dist_to_ph3_structural_trendline,ph1_structural_trendline_age,ph1_structural_trendline_power,ph2_structural_trendline_age,ph2_structural_trendline_power,ph3_structural_trendline_age,ph3_structural_trendline_power,dist_to_pl1_micro_trendline,trendline_pl1_slope_micro,slope_pl1_velocity_micro,dist_to_pl2_micro_trendline,dist_to_pl3_micro_trendline,pl1_micro_trendline_age,pl1_micro_trendline_power,pl2_micro_trendline_age,pl2_micro_trendline_power,pl3_micro_trendline_age,pl3_micro_trendline_power,trendline_pl1_micro_r2,trendline_pl2_micro_r2,trendline_pl3_micro_r2,dist_to_pl1_structural_trendline,dist_to_pl2_structural_trendline,dist_to_pl3_structural_trendline,pl1_structural_trendline_age,pl1_structural_trendline_power,pl2_structural_trendline_age,pl2_structural_trendline_power,pl3_structural_trendline_age,pl3_structural_trendline_power,trendline_ph_micro_r2_integrity,trendline_pl_micro_r2_integrity,rel_vol_5,rel_vol_20,vol_slope_5,vol_slope_10,vol_slope_20,vol_efficiency_1,vol_efficiency_5,vol_z_20,vol_z_200,buy_pressure_5,sell_pressure_5,buy_pressure_15,sell_pressure_15,vol_friction_5,vol_friction_20,vol_acceleration_5,vol_acceleration_10,vol_acceleration_20,session_vol_ratio,weekday_vol_ratio,EMA_10_acceleration,EMA_20_acceleration,EMA_50_acceleration,EMA_100_acceleration,EMA_200_acceleration,ER_5,ER_10,ER_30,relative_velocity_delta,momentum_efficiency_ratio,RSI_7_momentum_efficiency,RSI_14_momentum_efficiency,RSI_21_momentum_efficiency,bull_momentum_mass,bear_momentum_mass,reach_m3_tier03,reach_m3_tier075,reach_m3_tier15,reach_m3_tier30,reach_m4_tier03,reach_m4_tier075,reach_m4_tier15,reach_m4_tier30,reach_m5_tier03,reach_m5_tier075,reach_m5_tier15,reach_m5_tier30,reach_m10_tier03,reach_m10_tier075,reach_m10_tier15,reach_m10_tier30,smoothness_highs_10,smoothness_lows_10,target_3m_call_03,target_3m_put_03,target_3m_call_075,target_3m_put_075,target_3m_call_15,target_3m_put_15,target_3m_call_30,target_3m_put_30,target_4m_call_03,target_4m_put_03,target_4m_call_075,target_4m_put_075,target_4m_call_15,target_4m_put_15,target_4m_call_30,target_4m_put_30,target_5m_call_03,target_5m_put_03,target_5m_call_075,target_5m_put_075,target_5m_call_15,target_5m_put_15,target_5m_call_30,target_5m_put_30,target_10m_call_03,target_10m_put_03,target_10m_call_075,target_10m_put_075,target_10m_call_15,target_10m_put_15,target_10m_call_30,target_10m_put_30,minutes_since_news
0,1704155340,0.000206,-0.286691,-0.100137,-0.055855,-0.072599,-0.134252,-0.039688,-0.233444,-0.022289,-0.281038,-0.011849,-0.308865,39.622120,52.380371,45.756104,0.352939,0.206896,0.199999,0.000439,NaN,1.382966,0.974632,-0.136024,14,0.00000,0.00011,0.000000,1.000000,0.0,0.534720,0.0,0.126199,0.992005,0.958571,0.284852,0.951057,0.309017,0.187500,0.687500,0.125,0.777778,0.687500,0.000000,0.3125,0.777778,0.062500,0.687500,0.2500,0.777778,0.035714,0.750000,0.214286,1.361111,0.200000,0.800000,0.000000,1.458333,-0.489496,-0.099213,NaN,0.148387,NaN,-0.182526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-0.061889,100.0,5.475516,4.815109,-0.053500,-0.021340,0.489130,0.450000,-0.055772,0.032160,NaN,0.912670,NaN,NaN,0.187500,0.125,0.687500,0.729638,1.000000,0.0,0.000000,0.697816,0.833333,0.166667,0.0000,0.502992,1.0000,0.000,0.0000,0.478631,0.250000,0.000000,0.7500,0.608693,0.941176,0.058824,0.0000,0.624670,0.062500,0.937500,0.00,0.569973,1.000000,0.000000,0.00,0.970294,0.750000,0.250000,0.00,0.963142,0.250000,0.000000,0.75,0.953768,0.730761,1.526316,0.014925,NaN,29.0,NaN,0.243056,5.0,0.646737,NaN,29.0,NaN,0.243056,5.0,0.646737,NaN,29.0,NaN,0.243056,5.0,0.646737,NaN,0.646737,NaN,0.243056,NaN,5.0,NaN,0.646737,NaN,0.243056,NaN,5.0,NaN,0.646737,NaN,0.243056,NaN,5.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,29.0,NaN,29.0,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.243056,0.0,0.0,-0.243056,-0.243056,5.0,0.646737,5.0,0.646737,5.0,0.646737,1.0,1.0,1.0,-0.243056,-0.243056,-0.243056,5.0,0.646737,5.0,0.646737,5.0,0.646737,NaN,1.0,0.681818,0.582524,-100.0,-100.0,-100.0,0.000000,4.545454e-07,-1.184954,NaN,0.454545,0.409091,0.246753,0.597403,0.000007,0.000003,100.0,-100.0,-100.000000,0.239910,0.069421,-0.118892,-0.064758,-0.029387,-0.015653,-0.008116,0.030303,0.047619,NaN,1.612728,-0.010218,0.024282,0.122512,NaN,0.0,0.000000,0.094323,0.235807,0.471614,0.943227,0.069120,0.172799,0.345598,0.691197,0.053966,0.134915,0.269830,0.539660,0.024311,0.060776,0.121553,0.243105,0.817387,0.898223,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1440.0
1,1704155460,0.000180,-0.318375,-0.035288,-0.042732,-0.043984,-0.125598,-0.031404,-0.246278,-0.019083,-0.308592,-0.010537,-0.345999,51.514057,52.380371,44.600498,0.312498,0.214285,0.199999,0.000373,NaN,1.250026,1.038914,-0.066711,14,0.00000,0.00011,0.000000,1.000000,0.0,0.611108,0.0,0.134851,0.990866,0.959067,0.283179,0.951057,0.309017,1.000000,0.000000,0.000,0.611111,0.000000,1.000000,0.0000,0.611111,0.687500,0.000000,0.3125,0.888889,0.666667,0.000000,0.333333,1.000000,0.793103,0.000000,0.206897,1.611111,-0.350184,-0.086811,NaN,0.047619,-0.159741,-0.182553,NaN,0.018182,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-0.066667,100.0,4.302839,4.413928,0.023935,0.038889,0.523256,0.494505,0.021451,0.014954,NaN,0.811218,NaN,NaN,1.000000,0.000,0.000000,0.570367,0.000000,0.0,1.000000,0.534720,0.187500,0.125000,0.6875,0.729638,1.0000,0.000,0.0000,0.697816,0.833333,0.166667,0.0000,0.502992,1.000000,0.000000,0.0000,0.478631,0.250000,0.000000,0.75,0.608693,0.941176,0.058824,0.00,0.624670,0.062500,0.937500,0.00,0.569973,1.000000,0.000000,0.00,0.970294,0.379306,2.000000,0.015385,NaN,31.0,NaN,0.277778,7.0,0.646737,NaN,31.0,NaN,0.277778,7.0,0.646737,NaN,31.0,NaN,0.277778,7.0,0.646737,NaN,0.646737,NaN,0.277778,NaN,7.0,NaN,0.646737,NaN,0.277778,NaN,7.0,NaN,0.646737,NaN,0.277778,NaN,7.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,31.0,NaN,31.0,NaN,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.277778,0.0,0.0,-0.277778,-0.277778,7.0,0.646737,7.0,0.646737,7.0,0.646737,1.0,1.0,1.0,-0.277778,-0.277778,-0.277778,7.0,0.646737,7.0,0.646737,7.0,0.646737,NaN,1.0,1.000000,0.618557,-100.0,-100.0,-100.0,0.000000,6.666667e-07,-0.960064,NaN,0.266667,0.333333,0.267606,0.605634,0.000011,0.000003,-100.0,-100.0,-100.000000,0.239910,0.069421,0.069393,0.026491,0.005486,0.001328,0.000232,0.090908,0.085714,0.018182,0.640893,-100.000000,-0.047333,0.075388,NaN,0.0,0.000000,0.093333,0.233332,0.466664,0.933329,0.067681,0.169202,0.338405,0.676810,0.052573,0.131432,0.262864,0.525728,0.023155,0.057886,0.115773,0.231546,0.982735,0.878192,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1440.0
2,1704155520,0.000168,-0.335725,-0.030960,-0.037492,-0.042674,-0.121856,-0.032355,-0.253738,-0.020058,-0.324363,-0.011187,-0.367337,23.808731,52.380371,44.600498,0.312498,0.214285,0.199999,0.000367,NaN,1.339737,1.077610,-0.006200,14,0.00007,0.00011,0.636364,0.363636,0.0,0.655315,-1.0,0.139173,0.990268,0.959314,0.282341,0.951057,0.309017,0.000000,1.000000,0.000,0.655319,1.000000,0.000000,0.0000,0.655319,0.187500,0.687500,0.1250,0.953192,0.647059,0.000000,0.352941,1.012766,0.214286,0.785714,0.000000,1.668085,-0.283896,-0.081455,NaN,0.047619,-0.156401,-0.183130,NaN,0.003077,NaN,NaN,NaN,NaN,NaN,NaN,1.666627,0.772050,-0.067460,100.0,1.960022,4.119159,0.031304,0.022626,0.535714,0.491803,0.029140,-0.008677,NaN,0.821712,NaN,NaN,0.000000,0.000,1.000000,0.611108,1.000000,0.0,0.000000,0.570367,0.000000,0.000000,1.0000,0.534720,0.1875,0.125,0.6875,0.729638,1.000000,0.000000,0.0000,0.697816,0.833333,0.166667,0.0000,0.502992,1.000000,0.000000,0.00,0.478631,0.250000,0.000000,0.75,0.608693,0.941176,0.058824,0.00,0.624670,0.062500,0.937500,0.00,0.569973,0.947353,0.833333,0.083333,NaN,32.0,NaN,0.297872,8.0,0.646737,NaN,32.0,NaN,0.297872,8.0,0.646737,NaN,32.0,NaN,0.297872,8.0,0.646737,NaN,0.646737,NaN,0.297872,NaN,8.0,NaN,0.646737,NaN,0.297872,NaN,8.0,NaN,0.646737,NaN,0.297872,NaN,8.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,32.0,NaN,32.0,NaN,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.297872,0.0,0.0,-0.297872,-0.297872,8.0,0.646737,8.0,0.646737,8.0,0.646737,1.0,1.0,1.0,-0.297872,-0.297872,-0.297872,8.0,0.646737,8.0,0.646737,8.0,0.646737,NaN,1.0,1.000000,0.625000,-100.0,-100.0,-100.0,0.000023,3.333333e-06,-0.917052,NaN,0.266667,0.333333,0.275362,0.594203,0.000011,0.000003,100.0,-100.0,-86.276886,0.239910,0.069421,0.069177,0.029926,0.007333,0.002231,0.000662,0.999980,0.207547,0.003077,0.532870,-100.000000,0.019113,0.150140,NaN,0.0,0.332892,0.093130,0.232826,0.465651,0.931303,0.067464,0.168659,0.337319,0.674637,0.052145,0.130362,0.260724,0.521447,0.022691,0.056726,0.113453,0.226906,1.000000,0.866590,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1440.0
3,1704155580,0.000159,-0.588091,-0.072679,-0.238860,-0.064895,-0.344935,-0.042799,-0.500423,-0.025807,-0.583815,-0.014234,-0.634721,33.331779,50.768684,50.531349,0.062500,0.071428,0.066666,0.000324,NaN,1.435649,0.823938,-0.264829,14,0.00009,0.00015,0.600000,0.400000,0.0,0.945940,-1.0,0.143493,0.989651,0.959560,0.281504,0.951057,0.309017,0.733333,0.266667,0.000,0.945946,0.266667,0.733333,0.0000,0.945946,0.266667,0.733333,0.0000,0.945946,0.062500,0.937500,0.000000,1.009009,0.178571,0.750000,0.071429,1.765766,-0.247190,-0.296167,NaN,0.015385,-0.179290,-0.417325,NaN,0.018405,NaN,NaN,NaN,NaN,NaN,NaN,1.666636,0.931025,-0.055319,100.0,-1.289349,2.456202,-0.016815,-0.031831,1.034483,0.962567,0.004044,-0.015016,NaN,0.755783,NaN,NaN,0.636364,0.000,0.363636,0.655315,0.000000,0.0,1.000000,0.611108,1.000000,0.000000,0.0000,0.570367,0.0000,0.000,1.0000,0.534720,0.187500,0.125000,0.6875,0.729638,1.000000,0.000000,0.0000,0.697816,0.833333,0.166667,0.00,0.502992,1.000000,0.000000,0.00,0.478631,0.250000,0.000000,0.75,0.608693,0.941176,0.058824,0.00,0.624670,1.142833,1.426471,0.067796,NaN,33.0,NaN,0.063063,9.0,0.646737,NaN,33.0,NaN,0.063063,9.0,0.646737,NaN,33.0,NaN,0.063063,9.0,0.646737,NaN,0.646737,NaN,0.063063,NaN,9.0,NaN,0.646737,NaN,0.063063,NaN,9.0,NaN,0.646737,NaN,0.063063,NaN,9.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,33.0,NaN,33.0,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.063063,0.0,0.0,-0.063063,-0.063063,9.0,0.646737,9.0,0.646737,9.0,0.646737,1.0,1.0,1.0,-0.063063,-0.063063,-0.063063,9.0,0.646737,9.0,0.646737,9.0,0.646737,NaN,1.0,1.764706,1.224490,-100.0,-100.0,-100.0,0.000015,2.352941e-06,0.558138,NaN,0.000000,0.647059,0.263889,0.652778,0.000009,0.000003,100.0,-100.0,100.000000,0.479821,0.138842,-0.032424,-0.019522,-0.012292,-0.007637,-0.004301,0.999975,0.024390,0.018405,1.460108,0.045095,0.015997,0.046665,NaN,0.0,0.315937,0.093935,0.234836,0.469673,0.939346,0.068028,0.170071,0.340141,0.680282,0.052565,0.131412,0.262824,0.525648,0.022591,0.056479,0.112957,0.225915,1.000000,0.871843,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1440.0
4,1704155640,0.000154,-1.024133,-0.190746,-0.572071,-0.128246,-0.731247,-0.070222,-0.930065,-0.040117,-1.032869,-0.021578,-1.095050,31.248632,34.861938,39.758533,0.000000,0.000000,0.000000,0.000278,NaN,1.651596,0.335855,-0.660987,14,0.00022,0.00022,1.000000,0.000000,0.0,1.425917,-1.0,0.147809,0.989016,0.959805,0.280667,0.951057,0.309017,0.727273,0.272727,0.000,1.425926,0.818182,0.181818,0.0000,1.425926,1.000000,0.000000,0.0000,1.425926,0.454545,0.545455,0.000000,1.425926,0.363636,0.636364,0.000000,2.138889,-0.262809,-0.663336,NaN,0.036496,-0.193290,-0.825678,NaN,0.015385,NaN,NaN,NaN,NaN,NaN,NaN,2.244875,2.062481,-0.027027,100.0,-13.692409,-12.570278,-0.116760,-0.150835,1.011236,0.947368,-0.057727,-0.034074,NaN,0.681444,NaN,NaN,0.600000,0.000,0.400000,0.945940,0.636364,0.0,0.363636,0.655315,0.000000,0.000000,1.0000,0.611108,1.0000,0.000,0.0000,0.570367,0.000000,0.000000,1.0000,0.534720,0.187500,0.125000,0.6875,0.729638,1.000000,0.000000,0.00,0.697816,0.833333,0.166667,0.00,0.502992,1.000000,0.000000,0.00,0.478631,0.250000,0.000000,0.75,0.608693,3.454451,0.341463,0.157143,NaN,34.0,NaN,-0.388889,10.0,0.646737,NaN,34.0,NaN,-0.388889,10.0,0.646737,NaN,34.0,NaN,-0.388889,10.0,0.646737,NaN,0.646737,NaN,-0.388889,NaN,10.0,NaN,0.646737,NaN,-0.388889,NaN,10.0,NaN,0.646737,NaN,-0.388889,NaN,10.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,34.0,NaN,34.0,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.388889,0.0,0.0,0.388889,0.388889,10.0,0.646737,10.0,0.646737,10.0,0.646737,1.0,1.0,1.0,0.388889,0.388889,0.388889,10.0,0.646737,10.0,0.646737,10.0,0.646737,NaN,1.0,1.500000,1.237113,100.0,-100.0,-100.0,0.000037,5.500000e-06,0.596796,NaN,0.000000,0.850000,0.256757,0.662162,0.000011,0.000004,100.0,100.0,100.000000,0.479821,0.138842,-0.155458,-0.084262,-0.038818,-0.021034,-0.011041,0.999991,0.227272,0.015385,3.921232,0.011992,0.091827,0.149291,NaN,0.0,0.790489,0.096285,0.240712,0.481423,0.962847,0.070054,0.175134,0.350268,0.700536,0.054226,0.135564,0.271128,0.542256,0.023176,0.057940,0.115879,0.231759,1.000000,0.811167,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1440.0

In [4]:
# convert the time column from unix to human readable format
df['time'] = pd.to_datetime(df['time'], unit='s')
df.head()

,time,ATR_14,dist_to_vwap_norm,EMA_10_slope_norm,dist_to_EMA_10_norm,EMA_20_slope_norm,dist_to_EMA_20_norm,EMA_50_slope_norm,dist_to_EMA_50_norm,EMA_100_slope_norm,dist_to_EMA_100_norm,EMA_200_slope_norm,dist_to_EMA_200_norm,RSI_7,RSI_14,RSI_21,stoch_7_cycle_phase,stoch_14_cycle_phase,stoch_21_cycle_phase,BB_width,BB_squeeze_rank,dist_to_bb_upper_norm,dist_to_bb_lower_norm,dist_to_sma10,asset_id,body_size,total_range,body_ratio,top_wick_ratio,bottom_wick_ratio,relative_size,candle_direction,minute_sin,minute_cos,week_min_sin,week_min_cos,day_sin,day_cos,M2_Body_Ratio,M2_Top_Wick_Ratio,M2_Bottom_Wick_Ratio,M2_Relative_Size,M3_Body_Ratio,M3_Top_Wick_Ratio,M3_Bottom_Wick_Ratio,M3_Relative_Size,M5_Body_Ratio,M5_Top_Wick_Ratio,M5_Bottom_Wick_Ratio,M5_Relative_Size,M10_Body_Ratio,M10_Top_Wick_Ratio,M10_Bottom_Wick_Ratio,M10_Relative_Size,M15_Body_Ratio,M15_Top_Wick_Ratio,M15_Bottom_Wick_Ratio,M15_Relative_Size,EMA_15_slope_norm,dist_to_EMA_15_norm,RSI_15_proxy,M15_energy_ratio,EMA_30_slope_norm,dist_to_EMA_30_norm,RSI_30_proxy,M30_energy_ratio,H1_Volatility_Rank,H1_Body_Avg,H1_Efficiency_Ratio,H1_Trend_Direction,H1_Range_Cleanliness,H1_Gap_to_VWAP,M1_Velocity_vs_M5,M1_Velocity_vs_M15,M1_Volatility_Acceleration,M1_Spread_Tax_Ratio,RSI_M1_vs_M5_delta,RSI_M1_vs_M15_delta,Slope_M1_vs_M5_delta,Slope_M1_vs_M15_delta,Vol_M1_vs_M15_ratio,Vol_M1_vs_M30_ratio,Accel_M2_to_M5,Accel_M5_to_M15,Accel_M15_to_M60,Squeeze_Flow_M1_to_M10,Squeeze_Flow_M10_to_M30,Squeeze_Flow_M30_to_M200,body_ratio_lag_1,wick_low_lag_1,wick_high_lag_1,size_atr_lag_1,body_ratio_lag_2,wick_low_lag_2,wick_high_lag_2,size_atr_lag_2,body_ratio_lag_3,wick_low_lag_3,wick_high_lag_3,size_atr_lag_3,body_ratio_lag_4,wick_low_lag_4,wick_high_lag_4,size_atr_lag_4,body_ratio_lag_5,wick_low_lag_5,wick_high_lag_5,size_atr_lag_5,body_ratio_lag_6,wick_low_lag_6,wick_high_lag_6,size_atr_lag_6,body_ratio_lag_7,wick_low_lag_7,wick_high_lag_7,size_atr_lag_7,body_ratio_lag_8,wick_low_lag_8,wick_high_lag_8,size_atr_lag_8,body_ratio_lag_9,wick_low_lag_9,wick_high_lag_9,size_atr_lag_9,body_ratio_lag_10,wick_low_lag_10,wick_high_lag_10,size_atr_lag_10,pullback_intensity,wick_pressure_ratio,momentum_cleanliness,dist_to_ph1_micro_horizontal,ph1_micro_horizontal_age,ph1_micro_horizontal_power,dist_to_pl1_micro_horizontal,pl1_micro_horizontal_age,pl1_micro_horizontal_power,dist_to_ph2_micro_horizontal,ph2_micro_horizontal_age,ph2_micro_horizontal_power,dist_to_pl2_micro_horizontal,pl2_micro_horizontal_age,pl2_micro_horizontal_power,dist_to_ph3_micro_horizontal,ph3_micro_horizontal_age,ph3_micro_horizontal_power,dist_to_pl3_micro_horizontal,pl3_micro_horizontal_age,pl3_micro_horizontal_power,ph1_structural_horizontal_power,pl1_structural_horizontal_power,dist_to_ph1_structural_horizontal,dist_to_pl1_structural_horizontal,ph1_structural_horizontal_age,pl1_structural_horizontal_age,ph2_structural_horizontal_power,pl2_structural_horizontal_power,dist_to_ph2_structural_horizontal,dist_to_pl2_structural_horizontal,ph2_structural_horizontal_age,pl2_structural_horizontal_age,ph3_structural_horizontal_power,pl3_structural_horizontal_power,dist_to_ph3_structural_horizontal,dist_to_pl3_structural_horizontal,ph3_structural_horizontal_age,pl3_structural_horizontal_age,dist_to_00_pips,dist_to_50_pips,ph1_struct_touch_count,pl1_struct_touch_count,ph2_struct_touch_count,pl2_struct_touch_count,ph3_struct_touch_count,pl3_struct_touch_count,dist_to_ph1_micro_trendline,trendline_ph1_slope_micro,slope_ph1_velocity_micro,dist_to_ph2_micro_trendline,dist_to_ph3_micro_trendline,ph1_micro_trendline_age,ph1_micro_trendline_power,ph2_micro_trendline_age,ph2_micro_trendline_power,ph3_micro_trendline_age,ph3_micro_trendline_power,trendline_ph1_micro_r2,trendline_ph2_micro_r2,trendline_ph3_micro_r2,dist_to_ph1_structural_trendline,dist_to_ph2_structural_trendline,dist_to_ph3_structural_trendline,ph1_structural_trendline_age,ph1_structural_trendline_power,ph2_structural_trendline_age,ph2_structural_trendline_power,ph3_structural_trendline_age,ph3_structural_trendline_power,dist_to_pl1_micro_trendline,trendline_pl1_slope_micro,slope_pl1_velocity_micro,dist_to_pl2_micro_trendline,dist_to_pl3_micro_trendline,pl1_micro_trendline_age,pl1_micro_trendline_power,pl2_micro_trendline_age,pl2_micro_trendline_power,pl3_micro_trendline_age,pl3_micro_trendline_power,trendline_pl1_micro_r2,trendline_pl2_micro_r2,trendline_pl3_micro_r2,dist_to_pl1_structural_trendline,dist_to_pl2_structural_trendline,dist_to_pl3_structural_trendline,pl1_structural_trendline_age,pl1_structural_trendline_power,pl2_structural_trendline_age,pl2_structural_trendline_power,pl3_structural_trendline_age,pl3_structural_trendline_power,trendline_ph_micro_r2_integrity,trendline_pl_micro_r2_integrity,rel_vol_5,rel_vol_20,vol_slope_5,vol_slope_10,vol_slope_20,vol_efficiency_1,vol_efficiency_5,vol_z_20,vol_z_200,buy_pressure_5,sell_pressure_5,buy_pressure_15,sell_pressure_15,vol_friction_5,vol_friction_20,vol_acceleration_5,vol_acceleration_10,vol_acceleration_20,session_vol_ratio,weekday_vol_ratio,EMA_10_acceleration,EMA_20_acceleration,EMA_50_acceleration,EMA_100_acceleration,EMA_200_acceleration,ER_5,ER_10,ER_30,relative_velocity_delta,momentum_efficiency_ratio,RSI_7_momentum_efficiency,RSI_14_momentum_efficiency,RSI_21_momentum_efficiency,bull_momentum_mass,bear_momentum_mass,reach_m3_tier03,reach_m3_tier075,reach_m3_tier15,reach_m3_tier30,reach_m4_tier03,reach_m4_tier075,reach_m4_tier15,reach_m4_tier30,reach_m5_tier03,reach_m5_tier075,reach_m5_tier15,reach_m5_tier30,reach_m10_tier03,reach_m10_tier075,reach_m10_tier15,reach_m10_tier30,smoothness_highs_10,smoothness_lows_10,target_3m_call_03,target_3m_put_03,target_3m_call_075,target_3m_put_075,target_3m_call_15,target_3m_put_15,target_3m_call_30,target_3m_put_30,target_4m_call_03,target_4m_put_03,target_4m_call_075,target_4m_put_075,target_4m_call_15,target_4m_put_15,target_4m_call_30,target_4m_put_30,target_5m_call_03,target_5m_put_03,target_5m_call_075,target_5m_put_075,target_5m_call_15,target_5m_put_15,target_5m_call_30,target_5m_put_30,target_10m_call_03,target_10m_put_03,target_10m_call_075,target_10m_put_075,target_10m_call_15,target_10m_put_15,target_10m_call_30,target_10m_put_30,minutes_since_news
0,2024-01-02 00:29:00,0.000206,-0.286691,-0.100137,-0.055855,-0.072599,-0.134252,-0.039688,-0.233444,-0.022289,-0.281038,-0.011849,-0.308865,39.622120,52.380371,45.756104,0.352939,0.206896,0.199999,0.000439,NaN,1.382966,0.974632,-0.136024,14,0.00000,0.00011,0.000000,1.000000,0.0,0.534720,0.0,0.126199,0.992005,0.958571,0.284852,0.951057,0.309017,0.187500,0.687500,0.125,0.777778,0.687500,0.000000,0.3125,0.777778,0.062500,0.687500,0.2500,0.777778,0.035714,0.750000,0.214286,1.361111,0.200000,0.800000,0.000000,1.458333,-0.489496,-0.099213,NaN,0.148387,NaN,-0.182526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-0.061889,100.0,5.475516,4.815109,-0.053500,-0.021340,0.489130,0.450000,-0.055772,0.032160,NaN,0.912670,NaN,NaN,0.187500,0.125,0.687500,0.729638,1.000000,0.0,0.000000,0.697816,0.833333,0.166667,0.0000,0.502992,1.0000,0.000,0.0000,0.478631,0.250000,0.000000,0.7500,0.608693,0.941176,0.058824,0.0000,0.624670,0.062500,0.937500,0.00,0.569973,1.000000,0.000000,0.00,0.970294,0.750000,0.250000,0.00,0.963142,0.250000,0.000000,0.75,0.953768,0.730761,1.526316,0.014925,NaN,29.0,NaN,0.243056,5.0,0.646737,NaN,29.0,NaN,0.243056,5.0,0.646737,NaN,29.0,NaN,0.243056,5.0,0.646737,NaN,0.646737,NaN,0.243056,NaN,5.0,NaN,0.646737,NaN,0.243056,NaN,5.0,NaN,0.646737,NaN,0.243056,NaN,5.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,29.0,NaN,29.0,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.243056,0.0,0.0,-0.243056,-0.243056,5.0,0.646737,5.0,0.646737,5.0,0.646737,1.0,1.0,1.0,-0.243056,-0.243056,-0.243056,5.0,0.646737,5.0,0.646737,5.0,0.646737,NaN,1.0,0.681818,0.582524,-100.0,-100.0,-100.0,0.000000,4.545454e-07,-1.184954,NaN,0.454545,0.409091,0.246753,0.597403,0.000007,0.000003,100.0,-100.0,-100.000000,0.239910,0.069421,-0.118892,-0.064758,-0.029387,-0.015653,-0.008116,0.030303,0.047619,NaN,1.612728,-0.010218,0.024282,0.122512,NaN,0.0,0.000000,0.094323,0.235807,0.471614,0.943227,0.069120,0.172799,0.345598,0.691197,0.053966,0.134915,0.269830,0.539660,0.024311,0.060776,0.121553,0.243105,0.817387,0.898223,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1440.0
1,2024-01-02 00:31:00,0.000180,-0.318375,-0.035288,-0.042732,-0.043984,-0.125598,-0.031404,-0.246278,-0.019083,-0.308592,-0.010537,-0.345999,51.514057,52.380371,44.600498,0.312498,0.214285,0.199999,0.000373,NaN,1.250026,1.038914,-0.066711,14,0.00000,0.00011,0.000000,1.000000,0.0,0.611108,0.0,0.134851,0.990866,0.959067,0.283179,0.951057,0.309017,1.000000,0.000000,0.000,0.611111,0.000000,1.000000,0.0000,0.611111,0.687500,0.000000,0.3125,0.888889,0.666667,0.000000,0.333333,1.000000,0.793103,0.000000,0.206897,1.611111,-0.350184,-0.086811,NaN,0.047619,-0.159741,-0.182553,NaN,0.018182,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-0.066667,100.0,4.302839,4.413928,0.023935,0.038889,0.523256,0.494505,0.021451,0.014954,NaN,0.811218,NaN,NaN,1.000000,0.000,0.000000,0.570367,0.000000,0.0,1.000000,0.534720,0.187500,0.125000,0.6875,0.729638,1.0000,0.000,0.0000,0.697816,0.833333,0.166667,0.0000,0.502992,1.000000,0.000000,0.0000,0.478631,0.250000,0.000000,0.75,0.608693,0.941176,0.058824,0.00,0.624670,0.062500,0.937500,0.00,0.569973,1.000000,0.000000,0.00,0.970294,0.379306,2.000000,0.015385,NaN,31.0,NaN,0.277778,7.0,0.646737,NaN,31.0,NaN,0.277778,7.0,0.646737,NaN,31.0,NaN,0.277778,7.0,0.646737,NaN,0.646737,NaN,0.277778,NaN,7.0,NaN,0.646737,NaN,0.277778,NaN,7.0,NaN,0.646737,NaN,0.277778,NaN,7.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,31.0,NaN,31.0,NaN,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.277778,0.0,0.0,-0.277778,-0.277778,7.0,0.646737,7.0,0.646737,7.0,0.646737,1.0,1.0,1.0,-0.277778,-0.277778,-0.277778,7.0,0.646737,7.0,0.646737,7.0,0.646737,NaN,1.0,1.000000,0.618557,-100.0,-100.0,-100.0,0.000000,6.666667e-07,-0.960064,NaN,0.266667,0.333333,0.267606,0.605634,0.000011,0.000003,-100.0,-100.0,-100.000000,0.239910,0.069421,0.069393,0.026491,0.005486,0.001328,0.000232,0.090908,0.085714,0.018182,0.640893,-100.000000,-0.047333,0.075388,NaN,0.0,0.000000,0.093333,0.233332,0.466664,0.933329,0.067681,0.169202,0.338405,0.676810,0.052573,0.131432,0.262864,0.525728,0.023155,0.057886,0.115773,0.231546,0.982735,0.878192,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1440.0
2,2024-01-02 00:32:00,0.000168,-0.335725,-0.030960,-0.037492,-0.042674,-0.121856,-0.032355,-0.253738,-0.020058,-0.324363,-0.011187,-0.367337,23.808731,52.380371,44.600498,0.312498,0.214285,0.199999,0.000367,NaN,1.339737,1.077610,-0.006200,14,0.00007,0.00011,0.636364,0.363636,0.0,0.655315,-1.0,0.139173,0.990268,0.959314,0.282341,0.951057,0.309017,0.000000,1.000000,0.000,0.655319,1.000000,0.000000,0.0000,0.655319,0.187500,0.687500,0.1250,0.953192,0.647059,0.000000,0.352941,1.012766,0.214286,0.785714,0.000000,1.668085,-0.283896,-0.081455,NaN,0.047619,-0.156401,-0.183130,NaN,0.003077,NaN,NaN,NaN,NaN,NaN,NaN,1.666627,0.772050,-0.067460,100.0,1.960022,4.119159,0.031304,0.022626,0.535714,0.491803,0.029140,-0.008677,NaN,0.821712,NaN,NaN,0.000000,0.000,1.000000,0.611108,1.000000,0.0,0.000000,0.570367,0.000000,0.000000,1.0000,0.534720,0.1875,0.125,0.6875,0.729638,1.000000,0.000000,0.0000,0.697816,0.833333,0.166667,0.0000,0.502992,1.000000,0.000000,0.00,0.478631,0.250000,0.000000,0.75,0.608693,0.941176,0.058824,0.00,0.624670,0.062500,0.937500,0.00,0.569973,0.947353,0.833333,0.083333,NaN,32.0,NaN,0.297872,8.0,0.646737,NaN,32.0,NaN,0.297872,8.0,0.646737,NaN,32.0,NaN,0.297872,8.0,0.646737,NaN,0.646737,NaN,0.297872,NaN,8.0,NaN,0.646737,NaN,0.297872,NaN,8.0,NaN,0.646737,NaN,0.297872,NaN,8.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,32.0,NaN,32.0,NaN,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.297872,0.0,0.0,-0.297872,-0.297872,8.0,0.646737,8.0,0.646737,8.0,0.646737,1.0,1.0,1.0,-0.297872,-0.297872,-0.297872,8.0,0.646737,8.0,0.646737,8.0,0.646737,NaN,1.0,1.000000,0.625000,-100.0,-100.0,-100.0,0.000023,3.333333e-06,-0.917052,NaN,0.266667,0.333333,0.275362,0.594203,0.000011,0.000003,100.0,-100.0,-86.276886,0.239910,0.069421,0.069177,0.029926,0.007333,0.002231,0.000662,0.999980,0.207547,0.003077,0.532870,-100.000000,0.019113,0.150140,NaN,0.0,0.332892,0.093130,0.232826,0.465651,0.931303,0.067464,0.168659,0.337319,0.674637,0.052145,0.130362,0.260724,0.521447,0.022691,0.056726,0.113453,0.226906,1.000000,0.866590,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1440.0
3,2024-01-02 00:33:00,0.000159,-0.588091,-0.072679,-0.238860,-0.064895,-0.344935,-0.042799,-0.500423,-0.025807,-0.583815,-0.014234,-0.634721,33.331779,50.768684,50.531349,0.062500,0.071428,0.066666,0.000324,NaN,1.435649,0.823938,-0.264829,14,0.00009,0.00015,0.600000,0.400000,0.0,0.945940,-1.0,0.143493,0.989651,0.959560,0.281504,0.951057,0.309017,0.733333,0.266667,0.000,0.945946,0.266667,0.733333,0.0000,0.945946,0.266667,0.733333,0.0000,0.945946,0.062500,0.937500,0.000000,1.009009,0.178571,0.750000,0.071429,1.765766,-0.247190,-0.296167,NaN,0.015385,-0.179290,-0.417325,NaN,0.018405,NaN,NaN,NaN,NaN,NaN,NaN,1.666636,0.931025,-0.055319,100.0,-1.289349,2.456202,-0.016815,-0.031831,1.034483,0.962567,0.004044,-0.015016,NaN,0.755783,NaN,NaN,0.636364,0.000,0.363636,0.655315,0.000000,0.0,1.000000,0.611108,1.000000,0.000000,0.0000,0.570367,0.0000,0.000,1.0000,0.534720,0.187500,0.125000,0.6875,0.729638,1.000000,0.000000,0.0000,0.697816,0.833333,0.166667,0.00,0.502992,1.000000,0.000000,0.00,0.478631,0.250000,0.000000,0.75,0.608693,0.941176,0.058824,0.00,0.624670,1.142833,1.426471,0.067796,NaN,33.0,NaN,0.063063,9.0,0.646737,NaN,33.0,NaN,0.063063,9.0,0.646737,NaN,33.0,NaN,0.063063,9.0,0.646737,NaN,0.646737,NaN,0.063063,NaN,9.0,NaN,0.646737,NaN,0.063063,NaN,9.0,NaN,0.646737,NaN,0.063063,NaN,9.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,33.0,NaN,33.0,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.063063,0.0,0.0,-0.063063,-0.063063,9.0,0.646737,9.0,0.646737,9.0,0.646737,1.0,1.0,1.0,-0.063063,-0.063063,-0.063063,9.0,0.646737,9.0,0.646737,9.0,0.646737,NaN,1.0,1.764706,1.224490,-100.0,-100.0,-100.0,0.000015,2.352941e-06,0.558138,NaN,0.000000,0.647059,0.263889,0.652778,0.000009,0.000003,100.0,-100.0,100.000000,0.479821,0.138842,-0.032424,-0.019522,-0.012292,-0.007637,-0.004301,0.999975,0.024390,0.018405,1.460108,0.045095,0.015997,0.046665,NaN,0.0,0.315937,0.093935,0.234836,0.469673,0.939346,0.068028,0.170071,0.340141,0.680282,0.052565,0.131412,0.262824,0.525648,0.022591,0.056479,0.112957,0.225915,1.000000,0.871843,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1440.0
4,2024-01-02 00:34:00,0.000154,-1.024133,-0.190746,-0.572071,-0.128246,-0.731247,-0.070222,-0.930065,-0.040117,-1.032869,-0.021578,-1.095050,31.248632,34.861938,39.758533,0.000000,0.000000,0.000000,0.000278,NaN,1.651596,0.335855,-0.660987,14,0.00022,0.00022,1.000000,0.000000,0.0,1.425917,-1.0,0.147809,0.989016,0.959805,0.280667,0.951057,0.309017,0.727273,0.272727,0.000,1.425926,0.818182,0.181818,0.0000,1.425926,1.000000,0.000000,0.0000,1.425926,0.454545,0.545455,0.000000,1.425926,0.363636,0.636364,0.000000,2.138889,-0.262809,-0.663336,NaN,0.036496,-0.193290,-0.825678,NaN,0.015385,NaN,NaN,NaN,NaN,NaN,NaN,2.244875,2.062481,-0.027027,100.0,-13.692409,-12.570278,-0.116760,-0.150835,1.011236,0.947368,-0.057727,-0.034074,NaN,0.681444,NaN,NaN,0.600000,0.000,0.400000,0.945940,0.636364,0.0,0.363636,0.655315,0.000000,0.000000,1.0000,0.611108,1.0000,0.000,0.0000,0.570367,0.000000,0.000000,1.0000,0.534720,0.187500,0.125000,0.6875,0.729638,1.000000,0.000000,0.00,0.697816,0.833333,0.166667,0.00,0.502992,1.000000,0.000000,0.00,0.478631,0.250000,0.000000,0.75,0.608693,3.454451,0.341463,0.157143,NaN,34.0,NaN,-0.388889,10.0,0.646737,NaN,34.0,NaN,-0.388889,10.0,0.646737,NaN,34.0,NaN,-0.388889,10.0,0.646737,NaN,0.646737,NaN,-0.388889,NaN,10.0,NaN,0.646737,NaN,-0.388889,NaN,10.0,NaN,0.646737,NaN,-0.388889,NaN,10.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,34.0,NaN,34.0,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.388889,0.0,0.0,0.388889,0.388889,10.0,0.646737,10.0,0.646737,10.0,0.646737,1.0,1.0,1.0,0.388889,0.388889,0.388889,10.0,0.646737,10.0,0.646737,10.0,0.646737,NaN,1.0,1.500000,1.237113,100.0,-100.0,-100.0,0.000037,5.500000e-06,0.596796,NaN,0.000000,0.850000,0.256757,0.662162,0.000011,0.000004,100.0,100.0,100.000000,0.479821,0.138842,-0.155458,-0.084262,-0.038818,-0.021034,-0.011041,0.999991,0.227272,0.015385,3.921232,0.011992,0.091827,0.149291,NaN,0.0,0.790489,0.096285,0.240712,0.481423,0.962847,0.070054,0.175134,0.350268,0.700536,0.054226,0.135564,0.271128,0.542256,0.023176,0.057940,0.115879,0.231759,1.000000,0.811167,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1440.0

In [1]:
# display rows where column 'target_3m_call_03' is equal to 1 and also display the time column 
# df[['target_3m_call_03']] == 1
viewingdf =df[df['target_3m_call_03'] == 1][['time', 'target_3m_call_03']]
# the above doesn't show all 100 it shows 5 rows at the top of the 100 and 5 at the bottom of the 100 what do i do
pd.set_option('display.max_rows', None)
viewingdf.tail(10)

NameError: name 'df' is not defined

In [ ]:
df = pd.read_csv("EURUSD_M1_v4.csv")
df

In [20]:
# import 
import pandas as pd
# see all columns in the .head() dataframe 
# i want to see all columns in the .head() how do i do that?
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# df = pd.read_parquet("EURUSD_M1_v4.parquet")
df = pd.read_parquet("EURCAD_M1_v4.parquet")
# display a certain date range from 2025-12-05 11:00:00 to 2025-12-05 16:00:00
df['time'] = pd.to_datetime(df['time'], unit='s')
df_filtered = df[(df['time'] >= '2025-12-05 12:51:00') & (df['time'] < '2025-12-05 12:54:00')]
df_filtered

,time,ATR_14,dist_to_vwap_norm,EMA_10_slope_norm,dist_to_EMA_10_norm,EMA_20_slope_norm,dist_to_EMA_20_norm,EMA_50_slope_norm,dist_to_EMA_50_norm,EMA_100_slope_norm,dist_to_EMA_100_norm,EMA_200_slope_norm,dist_to_EMA_200_norm,RSI_7,RSI_14,RSI_21,stoch_7_cycle_phase,stoch_14_cycle_phase,stoch_21_cycle_phase,BB_width,BB_squeeze_rank,dist_to_bb_upper_norm,dist_to_bb_lower_norm,dist_to_sma10,asset_id,body_size,total_range,body_ratio,top_wick_ratio,bottom_wick_ratio,relative_size,candle_direction,minute_sin,minute_cos,week_min_sin,week_min_cos,day_sin,day_cos,M2_Body_Ratio,M2_Top_Wick_Ratio,M2_Bottom_Wick_Ratio,M2_Relative_Size,M3_Body_Ratio,M3_Top_Wick_Ratio,M3_Bottom_Wick_Ratio,M3_Relative_Size,M5_Body_Ratio,M5_Top_Wick_Ratio,M5_Bottom_Wick_Ratio,M5_Relative_Size,M10_Body_Ratio,M10_Top_Wick_Ratio,M10_Bottom_Wick_Ratio,M10_Relative_Size,M15_Body_Ratio,M15_Top_Wick_Ratio,M15_Bottom_Wick_Ratio,M15_Relative_Size,M30_Body_Ratio,M30_Top_Wick_Ratio,M30_Bottom_Wick_Ratio,M30_Relative_Size,M60_Body_Ratio,M60_Top_Wick_Ratio,M60_Bottom_Wick_Ratio,M60_Relative_Size,EMA_15_slope_norm,dist_to_EMA_15_norm,RSI_15_proxy,M15_energy_ratio,EMA_30_slope_norm,dist_to_EMA_30_norm,RSI_30_proxy,M30_energy_ratio,H1_Volatility_Rank,H1_Body_Avg,H1_Efficiency_Ratio,H1_Trend_Direction,H1_Range_Cleanliness,H1_Gap_to_VWAP,M1_Velocity_vs_M5,M1_Velocity_vs_M15,M1_Volatility_Acceleration,M1_Spread_Tax_Ratio,RSI_M1_vs_M5_delta,RSI_M1_vs_M15_delta,Slope_M1_vs_M5_delta,Slope_M1_vs_M15_delta,Vol_M1_vs_M15_ratio,Vol_M1_vs_M30_ratio,Accel_M2_to_M5,Accel_M5_to_M15,Accel_M15_to_M60,Squeeze_Flow_M1_to_M10,Squeeze_Flow_M10_to_M30,Squeeze_Flow_M30_to_M200,body_ratio_lag_1,wick_low_lag_1,wick_high_lag_1,size_atr_lag_1,body_ratio_lag_2,wick_low_lag_2,wick_high_lag_2,size_atr_lag_2,body_ratio_lag_3,wick_low_lag_3,wick_high_lag_3,size_atr_lag_3,body_ratio_lag_4,wick_low_lag_4,wick_high_lag_4,size_atr_lag_4,body_ratio_lag_5,wick_low_lag_5,wick_high_lag_5,size_atr_lag_5,body_ratio_lag_6,wick_low_lag_6,wick_high_lag_6,size_atr_lag_6,body_ratio_lag_7,wick_low_lag_7,wick_high_lag_7,size_atr_lag_7,body_ratio_lag_8,wick_low_lag_8,wick_high_lag_8,size_atr_lag_8,body_ratio_lag_9,wick_low_lag_9,wick_high_lag_9,size_atr_lag_9,body_ratio_lag_10,wick_low_lag_10,wick_high_lag_10,size_atr_lag_10,pullback_intensity,wick_pressure_ratio,momentum_cleanliness,dist_to_ph1_micro_horizontal,ph1_micro_horizontal_age,ph1_micro_horizontal_power,dist_to_pl1_micro_horizontal,pl1_micro_horizontal_age,pl1_micro_horizontal_power,dist_to_ph2_micro_horizontal,ph2_micro_horizontal_age,ph2_micro_horizontal_power,dist_to_pl2_micro_horizontal,pl2_micro_horizontal_age,pl2_micro_horizontal_power,dist_to_ph3_micro_horizontal,ph3_micro_horizontal_age,ph3_micro_horizontal_power,dist_to_pl3_micro_horizontal,pl3_micro_horizontal_age,pl3_micro_horizontal_power,ph1_structural_horizontal_power,pl1_structural_horizontal_power,dist_to_ph1_structural_horizontal,dist_to_pl1_structural_horizontal,ph1_structural_horizontal_age,pl1_structural_horizontal_age,ph2_structural_horizontal_power,pl2_structural_horizontal_power,dist_to_ph2_structural_horizontal,dist_to_pl2_structural_horizontal,ph2_structural_horizontal_age,pl2_structural_horizontal_age,ph3_structural_horizontal_power,pl3_structural_horizontal_power,dist_to_ph3_structural_horizontal,dist_to_pl3_structural_horizontal,ph3_structural_horizontal_age,pl3_structural_horizontal_age,dist_to_00_pips,dist_to_50_pips,ph1_struct_touch_count,pl1_struct_touch_count,ph2_struct_touch_count,pl2_struct_touch_count,ph3_struct_touch_count,pl3_struct_touch_count,dist_to_ph1_micro_trendline,trendline_ph1_slope_micro,slope_ph1_velocity_micro,dist_to_ph2_micro_trendline,dist_to_ph3_micro_trendline,ph1_micro_trendline_age,ph1_micro_trendline_power,ph2_micro_trendline_age,ph2_micro_trendline_power,ph3_micro_trendline_age,ph3_micro_trendline_power,trendline_ph1_micro_r2,trendline_ph2_micro_r2,trendline_ph3_micro_r2,dist_to_ph1_structural_trendline,dist_to_ph2_structural_trendline,dist_to_ph3_structural_trendline,ph1_structural_trendline_age,ph1_structural_trendline_power,ph2_structural_trendline_age,ph2_structural_trendline_power,ph3_structural_trendline_age,ph3_structural_trendline_power,dist_to_pl1_micro_trendline,trendline_pl1_slope_micro,slope_pl1_velocity_micro,dist_to_pl2_micro_trendline,dist_to_pl3_micro_trendline,pl1_micro_trendline_age,pl1_micro_trendline_power,pl2_micro_trendline_age,pl2_micro_trendline_power,pl3_micro_trendline_age,pl3_micro_trendline_power,trendline_pl1_micro_r2,trendline_pl2_micro_r2,trendline_pl3_micro_r2,dist_to_pl1_structural_trendline,dist_to_pl2_structural_trendline,dist_to_pl3_structural_trendline,pl1_structural_trendline_age,pl1_structural_trendline_power,pl2_structural_trendline_age,pl2_structural_trendline_power,pl3_structural_trendline_age,pl3_structural_trendline_power,trendline_ph_micro_r2_integrity,trendline_pl_micro_r2_integrity,rel_vol_5,rel_vol_20,vol_slope_5,vol_slope_10,vol_slope_20,vol_efficiency_1,vol_efficiency_5,vol_z_20,vol_z_200,buy_pressure_5,sell_pressure_5,buy_pressure_15,sell_pressure_15,vol_friction_5,vol_friction_20,vol_acceleration_5,vol_acceleration_10,vol_acceleration_20,session_vol_ratio,weekday_vol_ratio,EMA_10_acceleration,EMA_20_acceleration,EMA_50_acceleration,EMA_100_acceleration,EMA_200_acceleration,ER_5,ER_10,ER_30,relative_velocity_delta,momentum_efficiency_ratio,RSI_7_momentum_efficiency,RSI_14_momentum_efficiency,RSI_21_momentum_efficiency,bull_momentum_mass,bear_momentum_mass,reach_m3_tier03,reach_m3_tier075,reach_m3_tier15,reach_m3_tier30,reach_m4_tier03,reach_m4_tier075,reach_m4_tier15,reach_m4_tier30,reach_m5_tier03,reach_m5_tier075,reach_m5_tier15,reach_m5_tier30,reach_m10_tier03,reach_m10_tier075,reach_m10_tier15,reach_m10_tier30,smoothness_highs_10,smoothness_lows_10,target_3m_call_03,target_3m_put_03,target_3m_call_075,target_3m_put_075,target_3m_call_15,target_3m_put_15,target_3m_call_30,target_3m_put_30,target_4m_call_03,target_4m_put_03,target_4m_call_075,target_4m_put_075,target_4m_call_15,target_4m_put_15,target_4m_call_30,target_4m_put_30,target_5m_call_03,target_5m_put_03,target_5m_call_075,target_5m_put_075,target_5m_call_15,target_5m_put_15,target_5m_call_30,target_5m_put_30,target_10m_call_03,target_10m_put_03,target_10m_call_075,target_10m_put_075,target_10m_call_15,target_10m_put_15,target_10m_call_30,target_10m_put_30,minutes_since_news
448238,2025-12-05 12:51:00,0.000261,-4.255005,-0.374667,-1.191140,-0.237087,-1.461604,-0.112434,-1.694295,-0.077755,-2.079217,-0.067367,-3.038471,33.333099,33.536301,40.303860,0.000000,0.000000,0.000000,0.000376,0.473611,2.804597,-0.459513,-1.296655,9,0.00028,0.00028,1.00,0.000000,0.000000,1.073969,-1.0,-0.220697,-0.975342,-0.551209,0.834367,-0.951057,0.309017,0.846154,0.153846,0.000000,1.495890,0.847826,0.152174,0.000000,1.764383,0.846154,0.153846,0.000000,1.994520,0.826923,0.173077,0.000000,1.99452,0.550000,0.45000,0.000000,2.301370,0.680000,0.320000,0.000000,2.876712,0.58427,0.415730,0.000000,3.413698,-0.619220,-1.356532,45.553822,0.178378,-0.232108,-1.581694,48.760162,0.16129,0.257292,0.350320,0.089317,-1.0,3.413698,-2.504655,2.545431,2.608671,0.000000,100.0,-9.032729,-11.891842,-0.207042,-0.238166,1.36800,1.444257,-0.154912,-0.031124,-0.151357,1.486687,1.073834,0.540619,0.142857,0.642857,0.214286,1.073969,0.125,0.583333,0.291667,0.923073,0.444444,0.000000,0.555556,1.016125,0.285714,0.714286,0.000000,1.079886,0.120000,0.68,0.200000,0.964184,0.379310,0.586207,0.034483,1.137251,0.583333,0.333333,0.083333,0.938544,0.333333,0.666667,0.000000,1.169912,0.347826,0.521739,0.130435,0.904491,0.370370,0.407407,0.222222,1.032783,1.521719,1.366197,0.325926,1.879452,3.0,1.129028,-0.920548,5.0,1.426992,1.879452,3.0,1.129028,-0.920548,5.0,1.426992,1.879452,3.0,1.129028,-0.920548,5.0,1.426992,2.061751,1.649419,1.879452,-0.920548,67.0,100.0,2.061751,1.649419,1.879452,-0.920548,67.0,100.0,2.061751,1.649419,1.879452,-0.920548,67.0,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,1.879452,0.0,0.0,1.879452,1.879452,3.0,1.129028,3.0,1.129028,3.0,1.129028,1.0,1.0,1.0,1.879452,1.879452,1.879452,67.0,2.061751,67.0,2.061751,67.0,2.061751,0.920548,0.0,0.0,0.920548,0.920548,5.0,1.426992,5.0,1.426992,5.0,1.426992,1.0,1.0,1.0,0.920548,0.920548,0.920548,100.0,1.649419,100.0,1.649419,100.0,1.649419,1.0,1.0,1.289593,1.414392,100.0,100.0,100.0,0.000005,0.000002,1.832366,1.008849,0.176471,0.823529,0.447541,0.552459,0.000002,9.305211e-07,100.0,100.0,100.0,1.064657,1.142937,-0.280331,-0.161862,-0.073719,-0.038077,-0.019557,0.499999,0.318182,0.16129,2.860792,0.024680,2.468831,0.153673,0.161094,0.0,0.447897,0.100091,0.250228,0.500455,1.00091,0.074693,0.186732,0.373464,0.746928,0.059869,0.149671,0.299343,0.598686,0.030232,0.075579,0.151159,0.302318,0.788073,0.763343,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1440.0
448239,2025-12-05 12:53:00,0.000264,-4.523612,-0.632679,-1.144026,-0.400121,-1.534046,-0.190136,-1.890025,-0.118326,-2.314770,-0.087648,-3.280428,28.799839,33.333073,37.233765,0.061538,0.056338,0.045454,0.000465,0.647222,3.168808,-0.312273,-1.328287,9,0.00021,0.00028,0.75,0.107143,0.142857,1.059456,-1.0,-0.229200,-0.973379,-0.549752,0.835328,-0.951057,0.309017,0.258065,0.612903,0.129032,1.172973,0.902439,0.000000,0.097561,1.551351,0.813559,0.118644,0.067797,2.232432,0.861538,0.076923,0.061538,2.45946,0.661972,0.28169,0.056338,2.686486,0.761364,0.193182,0.045455,3.329730,0.54902,0.411765,0.039216,3.859459,-0.874441,-1.380472,45.885094,0.269841,-0.460480,-1.716024,48.564495,0.21194,0.283681,0.355676,0.093379,-1.0,3.859459,-2.544428,1.478863,1.956504,0.010929,100.0,-6.986303,-11.057516,-0.258421,-0.446391,1.14486,1.207888,-0.171438,-0.187971,-0.173726,1.575080,1.205944,0.559983,0.714286,0.095238,0.190476,0.803276,1.000,0.000000,0.000000,1.073969,0.142857,0.642857,0.214286,1.073969,0.125000,0.583333,0.291667,0.923073,0.444444,0.00,0.555556,1.016125,0.285714,0.714286,0.000000,1.079886,0.120000,0.680000,0.200000,0.964184,0.379310,0.586207,0.034483,1.137251,0.583333,0.333333,0.083333,0.938544,0.333333,0.666667,0.000000,1.169912,3.368368,0.217391,0.240310,2.194595,5.0,1.129028,-1.248649,7.0,1.426992,2.194595,5.0,1.129028,-1.248649,7.0,1.426992,2.194595,5.0,1.129028,-1.248649,7.0,1.426992,2.061751,1.649419,2.194595,-1.248649,69.0,100.0,2.061751,1.649419,2.194595,-1.248649,69.0,100.0,2.061751,1.649419,2.194595,-1.248649,69.0,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,2.194595,0.0,0.0,2.194595,2.194595,5.0,1.129028,5.0,1.129028,5.0,1.129028,1.0,1.0,1.0,2.194595,2.194595,2.194595,69.0,2.061751,69.0,2.061751,69.0,2.061751,1.248649,0.0,0.0,1.248649,1.248649,7.0,1.426992,7.0,1.426992,7.0,1.426992,1.0,1.0,1.0,1.248649,1.248649,1.248649,100.0,1.649419,100.0,1.649419,100.0,1.649419,1.0,1.0,1.038136,1.198044,100.0,100.0,100.0,0.000004,0.000001,0.988486,0.324813,0.169492,0.830508,0.432217,0.567783,0.000002,9.902201e-07,100.0,-100.0,-100.0,0.915237,0.982525,-0.362272,-0.226902,-0.107555,-0.056047,-0.028085,0.356321,0.373333,0.21194,3.234884,0.076848,0.135171,0.130695,0.126190,0.0,0.813805,0.100817,0.252043,0.504085,1.00817,0.075716,0.189290,0.378580,0.757159,0.060656,0.151639,0.303278,0.606555,0.030469,0.076173,0.152346,0.304693,0.660664,0.661207,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1440.0

In [25]:
# display the info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992727 entries, 0 to 992726
Columns: 141 entries, time to asset_id
dtypes: bool(5), float64(115), int64(19), object(2)
memory usage: 1.0+ GB

In [31]:
# display the all the columns and the number of unique values in each column
#i want to see all the columns i am only seeing top 5 and bottom 5. 
for column in df.columns:
    unique_values = df[column].nunique()
    print(f"column: {column}, unique values: {unique_values}")

column: time, unique values: 561355
column: <OPEN>, unique values: 58746
column: <HIGH>, unique values: 58494
column: <LOW>, unique values: 58603
column: <CLOSE>, unique values: 58673
column: <TICKVOL>, unique values: 887
column: <SPREAD>, unique values: 284
column: <VOL>, unique values: 1
column: ATR_14, unique values: 15674
column: SMA_10, unique values: 428726
column: dist_to_sma10, unique values: 728970
column: EMA_10, unique values: 992727
column: EMA_10_slope, unique values: 992727
column: EMA_20, unique values: 992727
column: EMA_20_slope, unique values: 992727
column: EMA_50, unique values: 992727
column: EMA_50_slope, unique values: 992727
column: EMA_100, unique values: 992727
column: EMA_100_slope, unique values: 992727
column: EMA_200, unique values: 992727
column: EMA_200_slope, unique values: 992727
column: RSI_7, unique values: 87359
column: RSI_14, unique values: 214993
column: RSI_21, unique values: 325370
column: BB_width, unique values: 982269
column: BB_squeeze_rank, unique values: 2716
column: volatility_change, unique values: 613995
column: is_swing_h, unique values: 2
column: is_swing_l, unique values: 2
column: pivot_h1_price, unique values: 54354
column: dist_to_ph1, unique values: 392423
column: ph1_age, unique values: 64
column: pivot_h1_power, unique values: 257639
column: pivot_l1_price, unique values: 54331
column: dist_to_pl1, unique values: 393651
column: pl1_age, unique values: 74
column: pivot_l1_power, unique values: 256867
column: pivot_h2_price, unique values: 54347
column: dist_to_ph2, unique values: 400541
column: ph2_age, unique values: 64
column: pivot_h2_power, unique values: 258785
column: pivot_l2_price, unique values: 54296
column: dist_to_pl2, unique values: 401795
column: pl2_age, unique values: 74
column: pivot_l2_power, unique values: 258355
column: pivot_h3_price, unique values: 54346
column: dist_to_ph3, unique values: 410494
column: ph3_age, unique values: 64
column: pivot_h3_power, unique values: 260468
column: pivot_l3_price, unique values: 54247
column: dist_to_pl3, unique values: 411978
column: pl3_age, unique values: 74
column: pivot_l3_power, unique values: 259867
column: trendline_slope_resistance, unique values: 141328
column: trendline_slope_support, unique values: 140913
column: slope_velocity_resistance, unique values: 367609
column: slope_velocity_support, unique values: 371364
column: trendline_r2_resistance, unique values: 991130
column: trendline_r2_support, unique values: 991088
column: body_size, unique values: 1058
column: total_range, unique values: 1349
column: body_ratio, unique values: 23041
column: top_wick_ratio, unique values: 16835
column: bottom_wick_ratio, unique values: 16678
column: relative_size, unique values: 279182
column: is_healthy_bull, unique values: 2
column: is_healthy_bear, unique values: 2
column: bull_momentum_count, unique values: 4
column: bear_momentum_count, unique values: 4
column: body_ratio_lag_1, unique values: 18407
column: wick_low_lag_1, unique values: 13790
column: wick_high_lag_1, unique values: 13717
column: size_atr_lag_1, unique values: 256548
column: body_ratio_lag_2, unique values: 18580
column: wick_low_lag_2, unique values: 13870
column: wick_high_lag_2, unique values: 13720
column: size_atr_lag_2, unique values: 259489
column: body_ratio_lag_3, unique values: 18911
column: wick_low_lag_3, unique values: 14103
column: wick_high_lag_3, unique values: 14068
column: size_atr_lag_3, unique values: 262644
column: body_ratio_lag_4, unique values: 19419
column: wick_low_lag_4, unique values: 14305
column: wick_high_lag_4, unique values: 14313
column: size_atr_lag_4, unique values: 265557
column: body_ratio_lag_5, unique values: 19876
column: wick_low_lag_5, unique values: 14555
column: wick_high_lag_5, unique values: 14554
column: size_atr_lag_5, unique values: 268705
column: body_ratio_lag_6, unique values: 20102
column: wick_low_lag_6, unique values: 14695
column: wick_high_lag_6, unique values: 14664
column: size_atr_lag_6, unique values: 270073
column: body_ratio_lag_7, unique values: 20340
column: wick_low_lag_7, unique values: 14955
column: wick_high_lag_7, unique values: 14772
column: size_atr_lag_7, unique values: 271626
column: body_ratio_lag_8, unique values: 20396
column: wick_low_lag_8, unique values: 14906
column: wick_high_lag_8, unique values: 14827
column: size_atr_lag_8, unique values: 272309
column: body_ratio_lag_9, unique values: 20459
column: wick_low_lag_9, unique values: 14979
column: wick_high_lag_9, unique values: 14890
column: size_atr_lag_9, unique values: 272769
column: body_ratio_lag_10, unique values: 20590
column: wick_low_lag_10, unique values: 14984
column: wick_high_lag_10, unique values: 15022
column: size_atr_lag_10, unique values: 273364
column: avg_body_ratio_5, unique values: 952884
column: avg_volatility_5, unique values: 992538
column: avg_body_ratio_10, unique values: 976016
column: avg_volatility_10, unique values: 992645
column: avg_body_ratio_20, unique values: 979994
column: avg_volatility_20, unique values: 992685
column: avg_body_ratio_30, unique values: 980930
column: avg_volatility_30, unique values: 992679
column: avg_body_ratio_60, unique values: 981323
column: avg_volatility_60, unique values: 992684
column: avg_body_ratio_200, unique values: 983491
column: avg_volatility_200, unique values: 992697
column: touches_sma10, unique values: 1
column: close_sma_dist, unique values: 728970
column: pullback_intensity, unique values: 134492
column: wick_pressure_ratio, unique values: 939666
column: momentum_cleanliness, unique values: 128417
column: hour_sin, unique values: 20
column: hour_cos, unique values: 22
column: day_sin, unique values: 5
column: day_cos, unique values: 5
column: target_1m_call, unique values: 2
column: target_1m_put, unique values: 2
column: target_2m_call, unique values: 2
column: target_2m_put, unique values: 2
column: target_3m_call, unique values: 2
column: target_3m_put, unique values: 2
column: target_4m_call, unique values: 2
column: target_4m_put, unique values: 2
column: target_5m_call, unique values: 2
column: target_5m_put, unique values: 2
column: asset_id, unique values: 4

In [33]:
# display the all the columns and the number of unique values in each column that have less than 10 unique values
for column in df.columns:
    unique_values = df[column].nunique()
    if unique_values < 100:
     print(f"column: {column}, unique values: {unique_values}")

column: <VOL>, unique values: 1
column: is_swing_h, unique values: 2
column: is_swing_l, unique values: 2
column: ph1_age, unique values: 64
column: pl1_age, unique values: 74
column: ph2_age, unique values: 64
column: pl2_age, unique values: 74
column: ph3_age, unique values: 64
column: pl3_age, unique values: 74
column: is_healthy_bull, unique values: 2
column: is_healthy_bear, unique values: 2
column: bull_momentum_count, unique values: 4
column: bear_momentum_count, unique values: 4
column: touches_sma10, unique values: 1
column: hour_sin, unique values: 20
column: hour_cos, unique values: 22
column: day_sin, unique values: 5
column: day_cos, unique values: 5
column: target_1m_call, unique values: 2
column: target_1m_put, unique values: 2
column: target_2m_call, unique values: 2
column: target_2m_put, unique values: 2
column: target_3m_call, unique values: 2
column: target_3m_put, unique values: 2
column: target_4m_call, unique values: 2
column: target_4m_put, unique values: 2
column: target_5m_call, unique values: 2
column: target_5m_put, unique values: 2
column: asset_id, unique values: 4

In [ ]:
# display top 5 rows in the dataframe
# import 
import pandas as pd

df = pd.read_csv('training_data.csv')
df.head()

In [3]:
len(df.columns)

141

In [7]:
# display all column names from dataframe
df.columns.to_list()

['time',
 '<OPEN>',
 '<HIGH>',
 '<LOW>',
 '<CLOSE>',
 '<TICKVOL>',
 '<SPREAD>',
 '<VOL>',
 'ATR_14',
 'SMA_10',
 'dist_to_sma10',
 'EMA_10',
 'EMA_10_slope',
 'EMA_20',
 'EMA_20_slope',
 'EMA_50',
 'EMA_50_slope',
 'EMA_100',
 'EMA_100_slope',
 'EMA_200',
 'EMA_200_slope',
 'RSI_7',
 'RSI_14',
 'RSI_21',
 'BB_width',
 'BB_squeeze_rank',
 'volatility_change',
 'is_swing_h',
 'is_swing_l',
 'pivot_h1_price',
 'dist_to_ph1',
 'ph1_age',
 'pivot_h1_power',
 'pivot_l1_price',
 'dist_to_pl1',
 'pl1_age',
 'pivot_l1_power',
 'pivot_h2_price',
 'dist_to_ph2',
 'ph2_age',
 'pivot_h2_power',
 'pivot_l2_price',
 'dist_to_pl2',
 'pl2_age',
 'pivot_l2_power',
 'pivot_h3_price',
 'dist_to_ph3',
 'ph3_age',
 'pivot_h3_power',
 'pivot_l3_price',
 'dist_to_pl3',
 'pl3_age',
 'pivot_l3_power',
 'trendline_slope_resistance',
 'trendline_slope_support',
 'slope_velocity_resistance',
 'slope_velocity_support',
 'trendline_r2_resistance',
 'trendline_r2_support',
 'body_size',
 'total_range',
 'body_ratio',
 'top_wick_ratio',
 'bottom_wick_ratio',
 'relative_size',
 'is_healthy_bull',
 'is_healthy_bear',
 'bull_momentum_count',
 'bear_momentum_count',
 'body_ratio_lag_1',
 'wick_low_lag_1',
 'wick_high_lag_1',
 'size_atr_lag_1',
 'body_ratio_lag_2',
 'wick_low_lag_2',
 'wick_high_lag_2',
 'size_atr_lag_2',
 'body_ratio_lag_3',
 'wick_low_lag_3',
 'wick_high_lag_3',
 'size_atr_lag_3',
 'body_ratio_lag_4',
 'wick_low_lag_4',
 'wick_high_lag_4',
 'size_atr_lag_4',
 'body_ratio_lag_5',
 'wick_low_lag_5',
 'wick_high_lag_5',
 'size_atr_lag_5',
 'body_ratio_lag_6',
 'wick_low_lag_6',
 'wick_high_lag_6',
 'size_atr_lag_6',
 'body_ratio_lag_7',
 'wick_low_lag_7',
 'wick_high_lag_7',
 'size_atr_lag_7',
 'body_ratio_lag_8',
 'wick_low_lag_8',
 'wick_high_lag_8',
 'size_atr_lag_8',
 'body_ratio_lag_9',
 'wick_low_lag_9',
 'wick_high_lag_9',
 'size_atr_lag_9',
 'body_ratio_lag_10',
 'wick_low_lag_10',
 'wick_high_lag_10',
 'size_atr_lag_10',
 'avg_body_ratio_5',
 'avg_volatility_5',
 'avg_body_ratio_10',
 'avg_volatility_10',
 'avg_body_ratio_20',
 'avg_volatility_20',
 'avg_body_ratio_30',
 'avg_volatility_30',
 'avg_body_ratio_60',
 'avg_volatility_60',
 'avg_body_ratio_200',
 'avg_volatility_200',
 'touches_sma10',
 'close_sma_dist',
 'pullback_intensity',
 'wick_pressure_ratio',
 'momentum_cleanliness',
 'hour_sin',
 'hour_cos',
 'day_sin',
 'day_cos',
 'target_1m_call',
 'target_1m_put',
 'target_2m_call',
 'target_2m_put',
 'target_3m_call',
 'target_3m_put',
 'target_4m_call',
 'target_4m_put',
 'target_5m_call',
 'target_5m_put',
 'asset_id']

In [11]:
list1 = ['time',
 '<OPEN>',
 '<HIGH>',
 '<LOW>',
 '<CLOSE>',
 '<TICKVOL>',
 '<SPREAD>',
 '<VOL>',
 'ATR_14',
 'SMA_10',
 'dist_to_sma10',
 'EMA_10',
 'EMA_10_slope',
 'EMA_20',
 'EMA_20_slope',
 'EMA_50',
 'EMA_50_slope',
 'EMA_100',
 'EMA_100_slope',
 'EMA_200',
 'EMA_200_slope',
 'RSI_7',
 'RSI_14',
 'RSI_21',
 'BB_width',
 'BB_squeeze_rank',
 'volatility_change',
 'is_swing_h',
 'is_swing_l',
 'pivot_h1_price',
 'dist_to_ph1',
 'ph1_age',
 'pivot_h1_power',
 'pivot_l1_price',
 'dist_to_pl1',
 'pl1_age',
 'pivot_l1_power',
 'pivot_h2_price',
 'dist_to_ph2',
 'ph2_age',
 'pivot_h2_power',
 'pivot_l2_price',
 'dist_to_pl2',
 'pl2_age',
 'pivot_l2_power',
 'pivot_h3_price',
 'dist_to_ph3',
 'ph3_age',
 'pivot_h3_power',
 'pivot_l3_price',
 'dist_to_pl3',
 'pl3_age',
 'pivot_l3_power',
 'trendline_slope_resistance',
 'trendline_slope_support',
 'slope_velocity_resistance',
 'slope_velocity_support',
 'trendline_r2_resistance',
 'trendline_r2_support',
 'body_size',
 'total_range',
 'body_ratio',
 'top_wick_ratio',
 'bottom_wick_ratio',
 'relative_size',
 'is_healthy_bull',
 'is_healthy_bear',
 'bull_momentum_count',
 'bear_momentum_count',
 'body_ratio_lag_1',
 'wick_low_lag_1',
 'wick_high_lag_1',
 'size_atr_lag_1',
 'body_ratio_lag_2',
 'wick_low_lag_2',
 'wick_high_lag_2',
 'size_atr_lag_2',
 'body_ratio_lag_3',
 'wick_low_lag_3',
 'wick_high_lag_3',
 'size_atr_lag_3',
 'body_ratio_lag_4',
 'wick_low_lag_4',
 'wick_high_lag_4',
 'size_atr_lag_4',
 'body_ratio_lag_5',
 'wick_low_lag_5',
 'wick_high_lag_5',
 'size_atr_lag_5',
 'body_ratio_lag_6',
 'wick_low_lag_6',
 'wick_high_lag_6',
 'size_atr_lag_6',
 'body_ratio_lag_7',
 'wick_low_lag_7',
 'wick_high_lag_7',
 'size_atr_lag_7',
 'body_ratio_lag_8',
 'wick_low_lag_8',
 'wick_high_lag_8',
 'size_atr_lag_8',
 'body_ratio_lag_9',
 'wick_low_lag_9',
 'wick_high_lag_9',
 'size_atr_lag_9',
 'body_ratio_lag_10',
 'wick_low_lag_10',
 'wick_high_lag_10',
 'size_atr_lag_10',
 'avg_body_ratio_5',
 'avg_volatility_5',
 'avg_body_ratio_10',
 'avg_volatility_10',
 'avg_body_ratio_20',
 'avg_volatility_20',
 'avg_body_ratio_30',
 'avg_volatility_30',
 'avg_body_ratio_60',
 'avg_volatility_60',
 'avg_body_ratio_200',
 'avg_volatility_200',
 'touches_sma10',
 'close_sma_dist',
 'pullback_intensity',
 'wick_pressure_ratio',
 'momentum_cleanliness',
 'hour_sin',
 'hour_cos',
 'day_sin',
 'day_cos',
 'target_1m_call',
 'target_1m_put',
 'target_2m_call',
 'target_2m_put',
 'target_3m_call',
 'target_3m_put',
 'target_4m_call',
 'target_4m_put',
 'target_5m_call',
 'target_5m_put',
 'asset_id']
# make the ouput of the list1 be arranged horizontally not vertically
for item in list1:
    print(item, end=' ')

time <OPEN> <HIGH> <LOW> <CLOSE> <TICKVOL> <SPREAD> <VOL> ATR_14 SMA_10 dist_to_sma10 EMA_10 EMA_10_slope EMA_20 EMA_20_slope EMA_50 EMA_50_slope EMA_100 EMA_100_slope EMA_200 EMA_200_slope RSI_7 RSI_14 RSI_21 BB_width BB_squeeze_rank volatility_change is_swing_h is_swing_l pivot_h1_price dist_to_ph1 ph1_age pivot_h1_power pivot_l1_price dist_to_pl1 pl1_age pivot_l1_power pivot_h2_price dist_to_ph2 ph2_age pivot_h2_power pivot_l2_price dist_to_pl2 pl2_age pivot_l2_power pivot_h3_price dist_to_ph3 ph3_age pivot_h3_power pivot_l3_price dist_to_pl3 pl3_age pivot_l3_power trendline_slope_resistance trendline_slope_support slope_velocity_resistance slope_velocity_support trendline_r2_resistance trendline_r2_support body_size total_range body_ratio top_wick_ratio bottom_wick_ratio relative_size is_healthy_bull is_healthy_bear bull_momentum_count bear_momentum_count body_ratio_lag_1 wick_low_lag_1 wick_high_lag_1 size_atr_lag_1 body_ratio_lag_2 wick_low_lag_2 wick_high_lag_2 size_atr_lag_2 body_ratio_lag_3 wick_low_lag_3 wick_high_lag_3 size_atr_lag_3 body_ratio_lag_4 wick_low_lag_4 wick_high_lag_4 size_atr_lag_4 body_ratio_lag_5 wick_low_lag_5 wick_high_lag_5 size_atr_lag_5 body_ratio_lag_6 wick_low_lag_6 wick_high_lag_6 size_atr_lag_6 body_ratio_lag_7 wick_low_lag_7 wick_high_lag_7 size_atr_lag_7 body_ratio_lag_8 wick_low_lag_8 wick_high_lag_8 size_atr_lag_8 body_ratio_lag_9 wick_low_lag_9 wick_high_lag_9 size_atr_lag_9 body_ratio_lag_10 wick_low_lag_10 wick_high_lag_10 size_atr_lag_10 avg_body_ratio_5 avg_volatility_5 avg_body_ratio_10 avg_volatility_10 avg_body_ratio_20 avg_volatility_20 avg_body_ratio_30 avg_volatility_30 avg_body_ratio_60 avg_volatility_60 avg_body_ratio_200 avg_volatility_200 touches_sma10 close_sma_dist pullback_intensity wick_pressure_ratio momentum_cleanliness hour_sin hour_cos day_sin day_cos target_1m_call target_1m_put target_2m_call target_2m_put target_3m_call target_3m_put target_4m_call target_4m_put target_5m_call target_5m_put asset_id

In [22]:
# check if a column is in the dataframe
'pivot_h1_price' in df.columns

True

In [13]:
import pandas as pd
df = pd.read_csv('training_data_4.csv')
print(df['target_3m_call'].value_counts(normalize=True))

target_3m_call
0    0.67328
1    0.32672
Name: proportion, dtype: float64

In [9]:
df.shape

(992727, 140)

In [3]:
# check if a column exists

column_df = 'wick_pressure_ratio'

column_df in df.columns

True

In [ ]:
Index(['time', '<OPEN>', '<HIGH>', '<LOW>', '<CLOSE>', '<TICKVOL>', '<SPREAD>',
       '<VOL>', 'ATR_14', 'SMA_10', 'dist_to_sma10', 'EMA_10', 'EMA_10_slope',
       'EMA_20', 'EMA_20_slope', 'EMA_50', 'EMA_50_slope', 'EMA_100',
       'EMA_100_slope', 'EMA_200', 'EMA_200_slope', 'RSI_7', 'RSI_14',
       'RSI_21', 'BB_width', 'BB_squeeze_rank', 'is_swing_h', 'is_swing_l',
       'pivot_h1_price', 'dist_to_ph1', 'ph1_age', 'pivot_h2_price',
       'dist_to_ph2', 'ph2_age', 'pivot_h3_price', 'dist_to_ph3', 'ph3_age',
       'trendline_slope', 'slope_velocity', 'body_size', 'total_range',
       'body_ratio', 'top_wick_ratio', 'bottom_wick_ratio', 'relative_size',
       'is_healthy_bull', 'is_healthy_bear', 'bull_momentum_count',
       'bear_momentum_count', 'touches_sma10', 'close_sma_dist', 'hour_sin',
       'hour_cos', 'day_sin', 'day_cos', 'target_1m_call', 'target_1m_put',
       'target_2m_call', 'target_2m_put', 'target_3m_call', 'target_3m_put',
       'target_4m_call', 'target_4m_put', 'target_5m_call', 'target_5m_put',
       'asset_id'],
      dtype='object')